// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT ak.id, ak.created_at, ak.updated_at, ak.is_active,
       ak.user_id, ak.name, ak.prefix, ak.key_hash,
       ak.expires_at, ak.last_used_at,
       u.role AS user_role
FROM api_keys ak
JOIN users u ON u.id = ak.user_id AND u.is_active = true
WHERE ak.prefix = $1 AND ak.is_active = true
`

type GetAPIKeyByPrefixRow struct {
	ID         int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	IsActive   bool
	UserID     int64
	Name       string
	Prefix     string
	KeyHash    string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	UserRole   string
}

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i GetAPIKeyByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.UserRole,
	)
	return i, err
}

const listAPIKeysByUserID = `-- name: ListAPIKeysByUserID :many
SELECT id, created_at, updated_at, is_active, user_id, name, prefix, key_hash, expires_at, last_used_at
FROM api_keys
WHERE user_id = $1 AND is_active = true
ORDER BY id
`

func (q *Queries) ListAPIKeysByUserID(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKeyUsage = `-- name: TouchAPIKeyUsage :exec
UPDATE api_keys SET last_used_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchAPIKeyUsage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIKeyUsage, id)
	return err
}
