// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"
)

const getItemByCode = `-- name: GetItemByCode :one
SELECT id, created_at, updated_at, is_active, name, code, notes
FROM items
WHERE code = $1
`

func (q *Queries) GetItemByCode(ctx context.Context, code string) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByCode, code)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Name,
		&i.Code,
		&i.Notes,
	)
	return i, err
}
