// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	IsActive   bool
	UserID     int64
	Name       string
	Prefix     string
	KeyHash    string
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type Item struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IsActive  bool
	Name      string
	Code      string
	Notes     []byte
}

type User struct {
	ID           int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	IsActive     bool
	Email        string
	PasswordHash string
	Role         string
	LastLoginAt  pgtype.Timestamptz
}
