// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, is_active, email, password_hash, role, last_login_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, is_active, email, password_hash, role, last_login_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.LastLoginAt,
	)
	return i, err
}

const touchUserLogin = `-- name: TouchUserLogin :one
UPDATE users SET last_login_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, created_at, updated_at, is_active, email, password_hash, role, last_login_at
`

func (q *Queries) TouchUserLogin(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, touchUserLogin, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.LastLoginAt,
	)
	return i, err
}
